name: API Tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          mkdir -p reports
          pytest --tb=short --disable-warnings
        
      - name: Run tests in Docker
        run: |
          docker build -t api-test .
          docker run --rm api-test

      - name: upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test.log